spring:
  application:
    name: project-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
#      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8082

services:
  user-service:
    base-url: http://localhost:8081

logging:
  level:
    com.archsense: DEBUG